// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: character/character.proto

package character

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a new character
type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	RealUserId    *string                `protobuf:"bytes,2,opt,name=real_user_id,json=realUserId,proto3,oneof" json:"real_user_id,omitempty"` // If empty, creates an AI character
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarMediaId *string                `protobuf:"bytes,4,opt,name=avatar_media_id,json=avatarMediaId,proto3,oneof" json:"avatar_media_id,omitempty"`
	Meta          *string                `protobuf:"bytes,5,opt,name=meta,proto3,oneof" json:"meta,omitempty"` // JSON string with additional character data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_character_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_character_character_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCharacterRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *CreateCharacterRequest) GetRealUserId() string {
	if x != nil && x.RealUserId != nil {
		return *x.RealUserId
	}
	return ""
}

func (x *CreateCharacterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateCharacterRequest) GetAvatarMediaId() string {
	if x != nil && x.AvatarMediaId != nil {
		return *x.AvatarMediaId
	}
	return ""
}

func (x *CreateCharacterRequest) GetMeta() string {
	if x != nil && x.Meta != nil {
		return *x.Meta
	}
	return ""
}

// Request to get a character by ID
type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_character_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_character_character_proto_rawDescGZIP(), []int{1}
}

func (x *GetCharacterRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

// Request to get all characters for a user in a world
type GetUserCharactersInWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCharactersInWorldRequest) Reset() {
	*x = GetUserCharactersInWorldRequest{}
	mi := &file_character_character_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCharactersInWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCharactersInWorldRequest) ProtoMessage() {}

func (x *GetUserCharactersInWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_character_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCharactersInWorldRequest.ProtoReflect.Descriptor instead.
func (*GetUserCharactersInWorldRequest) Descriptor() ([]byte, []int) {
	return file_character_character_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserCharactersInWorldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserCharactersInWorldRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

// Request to update an existing character
type UpdateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	AvatarMediaId *string                `protobuf:"bytes,3,opt,name=avatar_media_id,json=avatarMediaId,proto3,oneof" json:"avatar_media_id,omitempty"`
	AvatarUrl     *string                `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	Meta          *string                `protobuf:"bytes,5,opt,name=meta,proto3,oneof" json:"meta,omitempty"` // JSON string with additional character data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterRequest) Reset() {
	*x = UpdateCharacterRequest{}
	mi := &file_character_character_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterRequest) ProtoMessage() {}

func (x *UpdateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_character_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_character_character_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCharacterRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *UpdateCharacterRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateCharacterRequest) GetAvatarMediaId() string {
	if x != nil && x.AvatarMediaId != nil {
		return *x.AvatarMediaId
	}
	return ""
}

func (x *UpdateCharacterRequest) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *UpdateCharacterRequest) GetMeta() string {
	if x != nil && x.Meta != nil {
		return *x.Meta
	}
	return ""
}

// Character representation
type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	RealUserId    *string                `protobuf:"bytes,3,opt,name=real_user_id,json=realUserId,proto3,oneof" json:"real_user_id,omitempty"` // Empty for AI characters
	IsAi          bool                   `protobuf:"varint,4,opt,name=is_ai,json=isAi,proto3" json:"is_ai,omitempty"`
	DisplayName   string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarMediaId *string                `protobuf:"bytes,6,opt,name=avatar_media_id,json=avatarMediaId,proto3,oneof" json:"avatar_media_id,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,7,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // Signed URL to avatar image
	Meta          *string                `protobuf:"bytes,8,opt,name=meta,proto3,oneof" json:"meta,omitempty"`                      // JSON string
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_character_character_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_character_character_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_character_character_proto_rawDescGZIP(), []int{4}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Character) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *Character) GetRealUserId() string {
	if x != nil && x.RealUserId != nil {
		return *x.RealUserId
	}
	return ""
}

func (x *Character) GetIsAi() bool {
	if x != nil {
		return x.IsAi
	}
	return false
}

func (x *Character) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Character) GetAvatarMediaId() string {
	if x != nil && x.AvatarMediaId != nil {
		return *x.AvatarMediaId
	}
	return ""
}

func (x *Character) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Character) GetMeta() string {
	if x != nil && x.Meta != nil {
		return *x.Meta
	}
	return ""
}

func (x *Character) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// List of characters
type CharacterList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*Character           `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterList) Reset() {
	*x = CharacterList{}
	mi := &file_character_character_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterList) ProtoMessage() {}

func (x *CharacterList) ProtoReflect() protoreflect.Message {
	mi := &file_character_character_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterList.ProtoReflect.Descriptor instead.
func (*CharacterList) Descriptor() ([]byte, []int) {
	return file_character_character_proto_rawDescGZIP(), []int{5}
}

func (x *CharacterList) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

// Health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_character_character_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_character_character_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_character_character_proto_rawDescGZIP(), []int{6}
}

// Health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_character_character_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_character_character_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_character_character_proto_rawDescGZIP(), []int{7}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_character_character_proto protoreflect.FileDescriptor

const file_character_character_proto_rawDesc = "" +
	"\n" +
	"\x19character/character.proto\x12\x11generia.character\"\xf1\x01\n" +
	"\x16CreateCharacterRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\x12%\n" +
	"\freal_user_id\x18\x02 \x01(\tH\x00R\n" +
	"realUserId\x88\x01\x01\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12+\n" +
	"\x0favatar_media_id\x18\x04 \x01(\tH\x01R\ravatarMediaId\x88\x01\x01\x12\x17\n" +
	"\x04meta\x18\x05 \x01(\tH\x02R\x04meta\x88\x01\x01B\x0f\n" +
	"\r_real_user_idB\x12\n" +
	"\x10_avatar_media_idB\a\n" +
	"\x05_meta\"8\n" +
	"\x13GetCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\"U\n" +
	"\x1fGetUserCharactersInWorldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\"\x8a\x02\n" +
	"\x16UpdateCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12+\n" +
	"\x0favatar_media_id\x18\x03 \x01(\tH\x01R\ravatarMediaId\x88\x01\x01\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x02R\tavatarUrl\x88\x01\x01\x12\x17\n" +
	"\x04meta\x18\x05 \x01(\tH\x03R\x04meta\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\x12\n" +
	"\x10_avatar_media_idB\r\n" +
	"\v_avatar_urlB\a\n" +
	"\x05_meta\"\xc7\x02\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\x12%\n" +
	"\freal_user_id\x18\x03 \x01(\tH\x00R\n" +
	"realUserId\x88\x01\x01\x12\x13\n" +
	"\x05is_ai\x18\x04 \x01(\bR\x04isAi\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12+\n" +
	"\x0favatar_media_id\x18\x06 \x01(\tH\x01R\ravatarMediaId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\a \x01(\tR\tavatarUrl\x12\x17\n" +
	"\x04meta\x18\b \x01(\tH\x02R\x04meta\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAtB\x0f\n" +
	"\r_real_user_idB\x12\n" +
	"\x10_avatar_media_idB\a\n" +
	"\x05_meta\"M\n" +
	"\rCharacterList\x12<\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x1c.generia.character.CharacterR\n" +
	"characters\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xf0\x03\n" +
	"\x10CharacterService\x12Z\n" +
	"\x0fCreateCharacter\x12).generia.character.CreateCharacterRequest\x1a\x1c.generia.character.Character\x12Z\n" +
	"\x0fUpdateCharacter\x12).generia.character.UpdateCharacterRequest\x1a\x1c.generia.character.Character\x12T\n" +
	"\fGetCharacter\x12&.generia.character.GetCharacterRequest\x1a\x1c.generia.character.Character\x12p\n" +
	"\x18GetUserCharactersInWorld\x122.generia.character.GetUserCharactersInWorldRequest\x1a .generia.character.CharacterList\x12\\\n" +
	"\vHealthCheck\x12%.generia.character.HealthCheckRequest\x1a&.generia.character.HealthCheckResponseB'Z%github.com/generia/api/grpc/characterb\x06proto3"

var (
	file_character_character_proto_rawDescOnce sync.Once
	file_character_character_proto_rawDescData []byte
)

func file_character_character_proto_rawDescGZIP() []byte {
	file_character_character_proto_rawDescOnce.Do(func() {
		file_character_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_character_character_proto_rawDesc), len(file_character_character_proto_rawDesc)))
	})
	return file_character_character_proto_rawDescData
}

var file_character_character_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_character_character_proto_goTypes = []any{
	(*CreateCharacterRequest)(nil),          // 0: generia.character.CreateCharacterRequest
	(*GetCharacterRequest)(nil),             // 1: generia.character.GetCharacterRequest
	(*GetUserCharactersInWorldRequest)(nil), // 2: generia.character.GetUserCharactersInWorldRequest
	(*UpdateCharacterRequest)(nil),          // 3: generia.character.UpdateCharacterRequest
	(*Character)(nil),                       // 4: generia.character.Character
	(*CharacterList)(nil),                   // 5: generia.character.CharacterList
	(*HealthCheckRequest)(nil),              // 6: generia.character.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 7: generia.character.HealthCheckResponse
}
var file_character_character_proto_depIdxs = []int32{
	4, // 0: generia.character.CharacterList.characters:type_name -> generia.character.Character
	0, // 1: generia.character.CharacterService.CreateCharacter:input_type -> generia.character.CreateCharacterRequest
	3, // 2: generia.character.CharacterService.UpdateCharacter:input_type -> generia.character.UpdateCharacterRequest
	1, // 3: generia.character.CharacterService.GetCharacter:input_type -> generia.character.GetCharacterRequest
	2, // 4: generia.character.CharacterService.GetUserCharactersInWorld:input_type -> generia.character.GetUserCharactersInWorldRequest
	6, // 5: generia.character.CharacterService.HealthCheck:input_type -> generia.character.HealthCheckRequest
	4, // 6: generia.character.CharacterService.CreateCharacter:output_type -> generia.character.Character
	4, // 7: generia.character.CharacterService.UpdateCharacter:output_type -> generia.character.Character
	4, // 8: generia.character.CharacterService.GetCharacter:output_type -> generia.character.Character
	5, // 9: generia.character.CharacterService.GetUserCharactersInWorld:output_type -> generia.character.CharacterList
	7, // 10: generia.character.CharacterService.HealthCheck:output_type -> generia.character.HealthCheckResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_character_character_proto_init() }
func file_character_character_proto_init() {
	if File_character_character_proto != nil {
		return
	}
	file_character_character_proto_msgTypes[0].OneofWrappers = []any{}
	file_character_character_proto_msgTypes[3].OneofWrappers = []any{}
	file_character_character_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_character_character_proto_rawDesc), len(file_character_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_character_character_proto_goTypes,
		DependencyIndexes: file_character_character_proto_depIdxs,
		MessageInfos:      file_character_character_proto_msgTypes,
	}.Build()
	File_character_character_proto = out.File
	file_character_character_proto_goTypes = nil
	file_character_character_proto_depIdxs = nil
}
