version: '3.8'

services:
  # Infrastructure Services
  postgres:
    image: postgres:14-alpine
    container_name: generia-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=generia
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - generia_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: generia-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - generia_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: generia-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    networks:
      - generia_network
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio
    container_name: generia-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - generia_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  consul:
    image: hashicorp/consul:latest
    container_name: generia-consul
    restart: always
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    networks:
      - generia_network
    healthcheck:
      test: ["CMD", "consul", "info"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    container_name: generia-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - generia_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: generia-jaeger
    restart: always
    ports:
      - "16686:16686"  # Web UI
      - "14268:14268"  # Collector HTTP
      - "6831:6831/udp"  # Collector for Jaeger client using compact Thrift protocol
    networks:
      - generia_network

  prometheus:
    image: prom/prometheus:latest
    container_name: generia-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - generia_network

  grafana:
    image: grafana/grafana:latest
    container_name: generia-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - generia_network
    depends_on:
      - prometheus

  # Backend Microservices
  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    container_name: generia-api-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - post-service
      - media-service
      - interaction-service
      - feed-service
      - cache-service
      - cdn-service
      - consul
      - jaeger
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - CONSUL_ADDRESS=consul:8500
      - JAEGER_HOST=jaeger:6831
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRATION=24h
    networks:
      - generia_network

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: generia-auth-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started
      kafka:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      - SERVICE_NAME=auth-service
      - SERVICE_PORT=8081
      - SERVICE_HOST=0.0.0.0
      - CONSUL_ADDRESS=consul:8500
      - JAEGER_HOST=jaeger:6831
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=generia
      - DB_SSL_MODE=disable
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRATION=24h
      - KAFKA_BROKERS=kafka:9092
    networks:
      - generia_network

  post-service:
    build:
      context: .
      dockerfile: services/post-service/Dockerfile
    container_name: generia-post-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      consul:
        condition: service_started
      kafka:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      - SERVICE_NAME=post-service
      - SERVICE_PORT=8082
      - SERVICE_HOST=0.0.0.0
      - CONSUL_ADDRESS=consul:8500
      - JAEGER_HOST=jaeger:6831
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=generia
      - DB_SSL_MODE=disable
      - KAFKA_BROKERS=kafka:9092
    networks:
      - generia_network

  media-service:
    build:
      context: .
      dockerfile: services/media-service/Dockerfile
    container_name: generia-media-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      consul:
        condition: service_started
      kafka:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      - SERVICE_NAME=media-service
      - SERVICE_PORT=8083
      - SERVICE_HOST=0.0.0.0
      - CONSUL_ADDRESS=consul:8500
      - JAEGER_HOST=jaeger:6831
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=generia
      - DB_SSL_MODE=disable
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=generia-images
      - MINIO_USE_SSL=false
      - KAFKA_BROKERS=kafka:9092
    networks:
      - generia_network

  interaction-service:
    build:
      context: .
      dockerfile: services/interaction-service/Dockerfile
    container_name: generia-interaction-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      mongodb:
        condition: service_started
      consul:
        condition: service_started
      kafka:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      - SERVICE_NAME=interaction-service
      - SERVICE_PORT=8084
      - SERVICE_HOST=0.0.0.0
      - CONSUL_ADDRESS=consul:8500
      - JAEGER_HOST=jaeger:6831
      - MONGODB_URI=mongodb://admin:password@mongodb:27017
      - MONGODB_DATABASE=generia_interactions
      - KAFKA_BROKERS=kafka:9092
    networks:
      - generia_network

  feed-service:
    build:
      context: .
      dockerfile: services/feed-service/Dockerfile
    container_name: generia-feed-service
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      redis:
        condition: service_healthy
      consul:
        condition: service_started
      kafka:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      - SERVICE_NAME=feed-service
      - SERVICE_PORT=8085
      - SERVICE_HOST=0.0.0.0
      - CONSUL_ADDRESS=consul:8500
      - JAEGER_HOST=jaeger:6831
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - KAFKA_BROKERS=kafka:9092
    networks:
      - generia_network

  cache-service:
    build:
      context: .
      dockerfile: services/cache-service/Dockerfile
    container_name: generia-cache-service
    restart: always
    ports:
      - "8086:8086"
    depends_on:
      redis:
        condition: service_healthy
      consul:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      - SERVICE_NAME=cache-service
      - SERVICE_PORT=8086
      - SERVICE_HOST=0.0.0.0
      - CONSUL_ADDRESS=consul:8500
      - JAEGER_HOST=jaeger:6831
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=1
    networks:
      - generia_network

  cdn-service:
    build:
      context: .
      dockerfile: services/cdn-service/Dockerfile
    container_name: generia-cdn-service
    restart: always
    ports:
      - "8087:8087"
    depends_on:
      consul:
        condition: service_started
      jaeger:
        condition: service_started
    environment:
      - SERVICE_NAME=cdn-service
      - SERVICE_PORT=8087
      - SERVICE_HOST=0.0.0.0
      - CONSUL_ADDRESS=consul:8500
      - JAEGER_HOST=jaeger:6831
      - CDN_DOMAIN=localhost
      - CDN_DEFAULT_TTL=86400
      - CDN_SIGNING_KEY=your_cdn_signing_key
    networks:
      - generia_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: generia-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - generia_network

volumes:
  postgres_data:
  redis_data:
  mongo_data:
  minio_data:
  kafka_data:
  grafana_data:

networks:
  generia_network:
    driver: bridge