// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: cache/cache.proto

package cache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_Status = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_Status = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_Status = 2
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cache_cache_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_cache_cache_proto_enumTypes[0]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{19, 0}
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // Время жизни в секундах
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_cache_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_cache_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_cache_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_cache_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_cache_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_cache_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type IncrementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // Значение для инкремента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementRequest) Reset() {
	*x = IncrementRequest{}
	mi := &file_cache_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementRequest) ProtoMessage() {}

func (x *IncrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementRequest.ProtoReflect.Descriptor instead.
func (*IncrementRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{6}
}

func (x *IncrementRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IncrementRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type IncrementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewValue      int64                  `protobuf:"varint,1,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementResponse) Reset() {
	*x = IncrementResponse{}
	mi := &file_cache_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementResponse) ProtoMessage() {}

func (x *IncrementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementResponse.ProtoReflect.Descriptor instead.
func (*IncrementResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{7}
}

func (x *IncrementResponse) GetNewValue() int64 {
	if x != nil {
		return x.NewValue
	}
	return 0
}

type DecrementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // Значение для декремента
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementRequest) Reset() {
	*x = DecrementRequest{}
	mi := &file_cache_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementRequest) ProtoMessage() {}

func (x *DecrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementRequest.ProtoReflect.Descriptor instead.
func (*DecrementRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{8}
}

func (x *DecrementRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DecrementRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DecrementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewValue      int64                  `protobuf:"varint,1,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementResponse) Reset() {
	*x = DecrementResponse{}
	mi := &file_cache_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementResponse) ProtoMessage() {}

func (x *DecrementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementResponse.ProtoReflect.Descriptor instead.
func (*DecrementResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{9}
}

func (x *DecrementResponse) GetNewValue() int64 {
	if x != nil {
		return x.NewValue
	}
	return 0
}

type AddToListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`      // Время жизни в секундах
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"` // Для сортированных наборов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToListRequest) Reset() {
	*x = AddToListRequest{}
	mi := &file_cache_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToListRequest) ProtoMessage() {}

func (x *AddToListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToListRequest.ProtoReflect.Descriptor instead.
func (*AddToListRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{10}
}

func (x *AddToListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddToListRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AddToListRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *AddToListRequest) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type AddToListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ListSize      int64                  `protobuf:"varint,2,opt,name=list_size,json=listSize,proto3" json:"list_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToListResponse) Reset() {
	*x = AddToListResponse{}
	mi := &file_cache_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToListResponse) ProtoMessage() {}

func (x *AddToListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToListResponse.ProtoReflect.Descriptor instead.
func (*AddToListResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{11}
}

func (x *AddToListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddToListResponse) GetListSize() int64 {
	if x != nil {
		return x.ListSize
	}
	return 0
}

type GetListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListRequest) Reset() {
	*x = GetListRequest{}
	mi := &file_cache_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRequest) ProtoMessage() {}

func (x *GetListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRequest.ProtoReflect.Descriptor instead.
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{12}
}

func (x *GetListRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListResponse) Reset() {
	*x = GetListResponse{}
	mi := &file_cache_cache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListResponse) ProtoMessage() {}

func (x *GetListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListResponse.ProtoReflect.Descriptor instead.
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{13}
}

func (x *GetListResponse) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GetListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type HSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields        map[string][]byte      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // Время жизни в секундах
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HSetRequest) Reset() {
	*x = HSetRequest{}
	mi := &file_cache_cache_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetRequest) ProtoMessage() {}

func (x *HSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetRequest.ProtoReflect.Descriptor instead.
func (*HSetRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{14}
}

func (x *HSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HSetRequest) GetFields() map[string][]byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *HSetRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type HSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HSetResponse) Reset() {
	*x = HSetResponse{}
	mi := &file_cache_cache_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetResponse) ProtoMessage() {}

func (x *HSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetResponse.ProtoReflect.Descriptor instead.
func (*HSetResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{15}
}

func (x *HSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"` // Если пусто, то вернуть все поля
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetRequest) Reset() {
	*x = HGetRequest{}
	mi := &file_cache_cache_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetRequest) ProtoMessage() {}

func (x *HGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetRequest.ProtoReflect.Descriptor instead.
func (*HGetRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{16}
}

func (x *HGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HGetRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Fields        map[string][]byte      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetResponse) Reset() {
	*x = HGetResponse{}
	mi := &file_cache_cache_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetResponse) ProtoMessage() {}

func (x *HGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetResponse.ProtoReflect.Descriptor instead.
func (*HGetResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{17}
}

func (x *HGetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *HGetResponse) GetFields() map[string][]byte {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_cache_cache_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{18}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=cache.HealthCheckResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_cache_cache_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_cache_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_cache_cache_proto_rawDescGZIP(), []int{19}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_cache_cache_proto protoreflect.FileDescriptor

const file_cache_cache_proto_rawDesc = "" +
	"\n" +
	"\x11cache/cache.proto\x12\x05cache\"F\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\vGetResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x10IncrementRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"0\n" +
	"\x11IncrementResponse\x12\x1b\n" +
	"\tnew_value\x18\x01 \x01(\x03R\bnewValue\":\n" +
	"\x10DecrementRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"0\n" +
	"\x11DecrementResponse\x12\x1b\n" +
	"\tnew_value\x18\x01 \x01(\x03R\bnewValue\"b\n" +
	"\x10AddToListRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"J\n" +
	"\x11AddToListResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tlist_size\x18\x02 \x01(\x03R\blistSize\"P\n" +
	"\x0eGetListRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"?\n" +
	"\x0fGetListResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa4\x01\n" +
	"\vHSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x06fields\x18\x02 \x03(\v2\x1e.cache.HSetRequest.FieldsEntryR\x06fields\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"(\n" +
	"\fHSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\vHGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\"\x9a\x01\n" +
	"\fHGetResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x127\n" +
	"\x06fields\x18\x02 \x03(\v2\x1f.cache.HGetResponse.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x14\n" +
	"\x12HealthCheckRequest\"\x85\x01\n" +
	"\x13HealthCheckResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.cache.HealthCheckResponse.StatusR\x06status\"3\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xc3\x04\n" +
	"\fCacheService\x12,\n" +
	"\x03Set\x12\x11.cache.SetRequest\x1a\x12.cache.SetResponse\x12,\n" +
	"\x03Get\x12\x11.cache.GetRequest\x1a\x12.cache.GetResponse\x125\n" +
	"\x06Delete\x12\x14.cache.DeleteRequest\x1a\x15.cache.DeleteResponse\x12>\n" +
	"\tIncrement\x12\x17.cache.IncrementRequest\x1a\x18.cache.IncrementResponse\x12>\n" +
	"\tDecrement\x12\x17.cache.DecrementRequest\x1a\x18.cache.DecrementResponse\x12>\n" +
	"\tAddToList\x12\x17.cache.AddToListRequest\x1a\x18.cache.AddToListResponse\x128\n" +
	"\aGetList\x12\x15.cache.GetListRequest\x1a\x16.cache.GetListResponse\x12/\n" +
	"\x04HSet\x12\x12.cache.HSetRequest\x1a\x13.cache.HSetResponse\x12/\n" +
	"\x04HGet\x12\x12.cache.HGetRequest\x1a\x13.cache.HGetResponse\x12D\n" +
	"\vHealthCheck\x12\x19.cache.HealthCheckRequest\x1a\x1a.cache.HealthCheckResponseB-Z+github.com/sdshorin/generia/api/proto/cacheb\x06proto3"

var (
	file_cache_cache_proto_rawDescOnce sync.Once
	file_cache_cache_proto_rawDescData []byte
)

func file_cache_cache_proto_rawDescGZIP() []byte {
	file_cache_cache_proto_rawDescOnce.Do(func() {
		file_cache_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_cache_proto_rawDesc), len(file_cache_cache_proto_rawDesc)))
	})
	return file_cache_cache_proto_rawDescData
}

var file_cache_cache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cache_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_cache_cache_proto_goTypes = []any{
	(HealthCheckResponse_Status)(0), // 0: cache.HealthCheckResponse.Status
	(*SetRequest)(nil),              // 1: cache.SetRequest
	(*SetResponse)(nil),             // 2: cache.SetResponse
	(*GetRequest)(nil),              // 3: cache.GetRequest
	(*GetResponse)(nil),             // 4: cache.GetResponse
	(*DeleteRequest)(nil),           // 5: cache.DeleteRequest
	(*DeleteResponse)(nil),          // 6: cache.DeleteResponse
	(*IncrementRequest)(nil),        // 7: cache.IncrementRequest
	(*IncrementResponse)(nil),       // 8: cache.IncrementResponse
	(*DecrementRequest)(nil),        // 9: cache.DecrementRequest
	(*DecrementResponse)(nil),       // 10: cache.DecrementResponse
	(*AddToListRequest)(nil),        // 11: cache.AddToListRequest
	(*AddToListResponse)(nil),       // 12: cache.AddToListResponse
	(*GetListRequest)(nil),          // 13: cache.GetListRequest
	(*GetListResponse)(nil),         // 14: cache.GetListResponse
	(*HSetRequest)(nil),             // 15: cache.HSetRequest
	(*HSetResponse)(nil),            // 16: cache.HSetResponse
	(*HGetRequest)(nil),             // 17: cache.HGetRequest
	(*HGetResponse)(nil),            // 18: cache.HGetResponse
	(*HealthCheckRequest)(nil),      // 19: cache.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 20: cache.HealthCheckResponse
	nil,                             // 21: cache.HSetRequest.FieldsEntry
	nil,                             // 22: cache.HGetResponse.FieldsEntry
}
var file_cache_cache_proto_depIdxs = []int32{
	21, // 0: cache.HSetRequest.fields:type_name -> cache.HSetRequest.FieldsEntry
	22, // 1: cache.HGetResponse.fields:type_name -> cache.HGetResponse.FieldsEntry
	0,  // 2: cache.HealthCheckResponse.status:type_name -> cache.HealthCheckResponse.Status
	1,  // 3: cache.CacheService.Set:input_type -> cache.SetRequest
	3,  // 4: cache.CacheService.Get:input_type -> cache.GetRequest
	5,  // 5: cache.CacheService.Delete:input_type -> cache.DeleteRequest
	7,  // 6: cache.CacheService.Increment:input_type -> cache.IncrementRequest
	9,  // 7: cache.CacheService.Decrement:input_type -> cache.DecrementRequest
	11, // 8: cache.CacheService.AddToList:input_type -> cache.AddToListRequest
	13, // 9: cache.CacheService.GetList:input_type -> cache.GetListRequest
	15, // 10: cache.CacheService.HSet:input_type -> cache.HSetRequest
	17, // 11: cache.CacheService.HGet:input_type -> cache.HGetRequest
	19, // 12: cache.CacheService.HealthCheck:input_type -> cache.HealthCheckRequest
	2,  // 13: cache.CacheService.Set:output_type -> cache.SetResponse
	4,  // 14: cache.CacheService.Get:output_type -> cache.GetResponse
	6,  // 15: cache.CacheService.Delete:output_type -> cache.DeleteResponse
	8,  // 16: cache.CacheService.Increment:output_type -> cache.IncrementResponse
	10, // 17: cache.CacheService.Decrement:output_type -> cache.DecrementResponse
	12, // 18: cache.CacheService.AddToList:output_type -> cache.AddToListResponse
	14, // 19: cache.CacheService.GetList:output_type -> cache.GetListResponse
	16, // 20: cache.CacheService.HSet:output_type -> cache.HSetResponse
	18, // 21: cache.CacheService.HGet:output_type -> cache.HGetResponse
	20, // 22: cache.CacheService.HealthCheck:output_type -> cache.HealthCheckResponse
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_cache_cache_proto_init() }
func file_cache_cache_proto_init() {
	if File_cache_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_cache_proto_rawDesc), len(file_cache_cache_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_cache_proto_goTypes,
		DependencyIndexes: file_cache_cache_proto_depIdxs,
		EnumInfos:         file_cache_cache_proto_enumTypes,
		MessageInfos:      file_cache_cache_proto_msgTypes,
	}.Build()
	File_cache_cache_proto = out.File
	file_cache_cache_proto_goTypes = nil
	file_cache_cache_proto_depIdxs = nil
}
