// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: world/world.proto

package world

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_world_world_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_world_world_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{15, 0}
}

// CreateWorldRequest is the request for creating a new world
type CreateWorldRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prompt          string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	CharactersCount int32                  `protobuf:"varint,5,opt,name=characters_count,json=charactersCount,proto3" json:"characters_count,omitempty"`
	PostsCount      int32                  `protobuf:"varint,6,opt,name=posts_count,json=postsCount,proto3" json:"posts_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateWorldRequest) Reset() {
	*x = CreateWorldRequest{}
	mi := &file_world_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorldRequest) ProtoMessage() {}

func (x *CreateWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorldRequest.ProtoReflect.Descriptor instead.
func (*CreateWorldRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWorldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorldRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorldRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateWorldRequest) GetCharactersCount() int32 {
	if x != nil {
		return x.CharactersCount
	}
	return 0
}

func (x *CreateWorldRequest) GetPostsCount() int32 {
	if x != nil {
		return x.PostsCount
	}
	return 0
}

// WorldResponse contains information about a world
type WorldResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prompt           string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	CreatorId        string                 `protobuf:"bytes,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	GenerationStatus string                 `protobuf:"bytes,6,opt,name=generation_status,json=generationStatus,proto3" json:"generation_status,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	UsersCount       int32                  `protobuf:"varint,8,opt,name=users_count,json=usersCount,proto3" json:"users_count,omitempty"`
	PostsCount       int32                  `protobuf:"varint,9,opt,name=posts_count,json=postsCount,proto3" json:"posts_count,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsJoined         bool                   `protobuf:"varint,12,opt,name=is_joined,json=isJoined,proto3" json:"is_joined,omitempty"`
	ImageUrl         string                 `protobuf:"bytes,13,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	IconUrl          string                 `protobuf:"bytes,14,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Params           *string                `protobuf:"bytes,15,opt,name=params,proto3,oneof" json:"params,omitempty"` // JSON string with full world description
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorldResponse) Reset() {
	*x = WorldResponse{}
	mi := &file_world_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldResponse) ProtoMessage() {}

func (x *WorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldResponse.ProtoReflect.Descriptor instead.
func (*WorldResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{1}
}

func (x *WorldResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorldResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorldResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorldResponse) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *WorldResponse) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *WorldResponse) GetGenerationStatus() string {
	if x != nil {
		return x.GenerationStatus
	}
	return ""
}

func (x *WorldResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorldResponse) GetUsersCount() int32 {
	if x != nil {
		return x.UsersCount
	}
	return 0
}

func (x *WorldResponse) GetPostsCount() int32 {
	if x != nil {
		return x.PostsCount
	}
	return 0
}

func (x *WorldResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WorldResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *WorldResponse) GetIsJoined() bool {
	if x != nil {
		return x.IsJoined
	}
	return false
}

func (x *WorldResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *WorldResponse) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *WorldResponse) GetParams() string {
	if x != nil && x.Params != nil {
		return *x.Params
	}
	return ""
}

// GetWorldRequest is the request for getting a world by ID
type GetWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorldRequest) Reset() {
	*x = GetWorldRequest{}
	mi := &file_world_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldRequest) ProtoMessage() {}

func (x *GetWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldRequest.ProtoReflect.Descriptor instead.
func (*GetWorldRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorldRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *GetWorldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetWorldsRequest is the request for getting all worlds available to a user
type GetWorldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // active, archived, all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorldsRequest) Reset() {
	*x = GetWorldsRequest{}
	mi := &file_world_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldsRequest) ProtoMessage() {}

func (x *GetWorldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldsRequest.ProtoReflect.Descriptor instead.
func (*GetWorldsRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorldsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWorldsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWorldsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetWorldsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// WorldsResponse contains a list of worlds
type WorldsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worlds        []*WorldResponse       `protobuf:"bytes,1,rep,name=worlds,proto3" json:"worlds,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldsResponse) Reset() {
	*x = WorldsResponse{}
	mi := &file_world_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldsResponse) ProtoMessage() {}

func (x *WorldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldsResponse.ProtoReflect.Descriptor instead.
func (*WorldsResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{4}
}

func (x *WorldsResponse) GetWorlds() []*WorldResponse {
	if x != nil {
		return x.Worlds
	}
	return nil
}

func (x *WorldsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// JoinWorldRequest is the request for joining a world
type JoinWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinWorldRequest) Reset() {
	*x = JoinWorldRequest{}
	mi := &file_world_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorldRequest) ProtoMessage() {}

func (x *JoinWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorldRequest.ProtoReflect.Descriptor instead.
func (*JoinWorldRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{5}
}

func (x *JoinWorldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinWorldRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

// JoinWorldResponse is the response for joining a world
type JoinWorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinWorldResponse) Reset() {
	*x = JoinWorldResponse{}
	mi := &file_world_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorldResponse) ProtoMessage() {}

func (x *JoinWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorldResponse.ProtoReflect.Descriptor instead.
func (*JoinWorldResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{6}
}

func (x *JoinWorldResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinWorldResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetGenerationStatusRequest is the request for getting the generation status of a world
type GetGenerationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationStatusRequest) Reset() {
	*x = GetGenerationStatusRequest{}
	mi := &file_world_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusRequest) ProtoMessage() {}

func (x *GetGenerationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{7}
}

func (x *GetGenerationStatusRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

// StageInfo represents information about a generation stage
type StageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageInfo) Reset() {
	*x = StageInfo{}
	mi := &file_world_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageInfo) ProtoMessage() {}

func (x *StageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageInfo.ProtoReflect.Descriptor instead.
func (*StageInfo) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{8}
}

func (x *StageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StageInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetGenerationStatusResponse is the response for getting the generation status of a world
type GetGenerationStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStage        string                 `protobuf:"bytes,2,opt,name=current_stage,json=currentStage,proto3" json:"current_stage,omitempty"`
	Stages              []*StageInfo           `protobuf:"bytes,3,rep,name=stages,proto3" json:"stages,omitempty"`
	TasksTotal          int32                  `protobuf:"varint,4,opt,name=tasks_total,json=tasksTotal,proto3" json:"tasks_total,omitempty"`
	TasksCompleted      int32                  `protobuf:"varint,5,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	TasksFailed         int32                  `protobuf:"varint,6,opt,name=tasks_failed,json=tasksFailed,proto3" json:"tasks_failed,omitempty"`
	TaskPredicted       int32                  `protobuf:"varint,7,opt,name=task_predicted,json=taskPredicted,proto3" json:"task_predicted,omitempty"`
	UsersCreated        int32                  `protobuf:"varint,8,opt,name=users_created,json=usersCreated,proto3" json:"users_created,omitempty"`
	PostsCreated        int32                  `protobuf:"varint,9,opt,name=posts_created,json=postsCreated,proto3" json:"posts_created,omitempty"`
	UsersPredicted      int32                  `protobuf:"varint,10,opt,name=users_predicted,json=usersPredicted,proto3" json:"users_predicted,omitempty"`
	PostsPredicted      int32                  `protobuf:"varint,11,opt,name=posts_predicted,json=postsPredicted,proto3" json:"posts_predicted,omitempty"`
	ApiCallLimitsLlm    int32                  `protobuf:"varint,12,opt,name=api_call_limits_llm,json=apiCallLimitsLlm,proto3" json:"api_call_limits_llm,omitempty"`
	ApiCallLimitsImages int32                  `protobuf:"varint,13,opt,name=api_call_limits_images,json=apiCallLimitsImages,proto3" json:"api_call_limits_images,omitempty"`
	ApiCallsMadeLlm     int32                  `protobuf:"varint,14,opt,name=api_calls_made_llm,json=apiCallsMadeLlm,proto3" json:"api_calls_made_llm,omitempty"`
	ApiCallsMadeImages  int32                  `protobuf:"varint,15,opt,name=api_calls_made_images,json=apiCallsMadeImages,proto3" json:"api_calls_made_images,omitempty"`
	LlmCostTotal        float64                `protobuf:"fixed64,16,opt,name=llm_cost_total,json=llmCostTotal,proto3" json:"llm_cost_total,omitempty"`
	ImageCostTotal      float64                `protobuf:"fixed64,17,opt,name=image_cost_total,json=imageCostTotal,proto3" json:"image_cost_total,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetGenerationStatusResponse) Reset() {
	*x = GetGenerationStatusResponse{}
	mi := &file_world_world_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusResponse) ProtoMessage() {}

func (x *GetGenerationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{9}
}

func (x *GetGenerationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetGenerationStatusResponse) GetCurrentStage() string {
	if x != nil {
		return x.CurrentStage
	}
	return ""
}

func (x *GetGenerationStatusResponse) GetStages() []*StageInfo {
	if x != nil {
		return x.Stages
	}
	return nil
}

func (x *GetGenerationStatusResponse) GetTasksTotal() int32 {
	if x != nil {
		return x.TasksTotal
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetTasksCompleted() int32 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetTasksFailed() int32 {
	if x != nil {
		return x.TasksFailed
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetTaskPredicted() int32 {
	if x != nil {
		return x.TaskPredicted
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetUsersCreated() int32 {
	if x != nil {
		return x.UsersCreated
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetPostsCreated() int32 {
	if x != nil {
		return x.PostsCreated
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetUsersPredicted() int32 {
	if x != nil {
		return x.UsersPredicted
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetPostsPredicted() int32 {
	if x != nil {
		return x.PostsPredicted
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetApiCallLimitsLlm() int32 {
	if x != nil {
		return x.ApiCallLimitsLlm
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetApiCallLimitsImages() int32 {
	if x != nil {
		return x.ApiCallLimitsImages
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetApiCallsMadeLlm() int32 {
	if x != nil {
		return x.ApiCallsMadeLlm
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetApiCallsMadeImages() int32 {
	if x != nil {
		return x.ApiCallsMadeImages
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetLlmCostTotal() float64 {
	if x != nil {
		return x.LlmCostTotal
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetImageCostTotal() float64 {
	if x != nil {
		return x.ImageCostTotal
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetGenerationStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// UpdateWorldImageRequest is the request for updating a world's image
type UpdateWorldImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	ImageUuid     string                 `protobuf:"bytes,2,opt,name=image_uuid,json=imageUuid,proto3" json:"image_uuid,omitempty"`
	IconUuid      string                 `protobuf:"bytes,3,opt,name=icon_uuid,json=iconUuid,proto3" json:"icon_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorldImageRequest) Reset() {
	*x = UpdateWorldImageRequest{}
	mi := &file_world_world_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorldImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorldImageRequest) ProtoMessage() {}

func (x *UpdateWorldImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorldImageRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorldImageRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateWorldImageRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *UpdateWorldImageRequest) GetImageUuid() string {
	if x != nil {
		return x.ImageUuid
	}
	return ""
}

func (x *UpdateWorldImageRequest) GetIconUuid() string {
	if x != nil {
		return x.IconUuid
	}
	return ""
}

// UpdateWorldImageResponse is the response for updating a world's image
type UpdateWorldImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorldImageResponse) Reset() {
	*x = UpdateWorldImageResponse{}
	mi := &file_world_world_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorldImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorldImageResponse) ProtoMessage() {}

func (x *UpdateWorldImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorldImageResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorldImageResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateWorldImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateWorldImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateWorldParamsRequest is the request for saving world parameters
type UpdateWorldParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Params        string                 `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"` // JSON string with generated parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorldParamsRequest) Reset() {
	*x = UpdateWorldParamsRequest{}
	mi := &file_world_world_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorldParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorldParamsRequest) ProtoMessage() {}

func (x *UpdateWorldParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorldParamsRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorldParamsRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateWorldParamsRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *UpdateWorldParamsRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

// UpdateWorldParamsResponse is the response for updating world params
type UpdateWorldParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorldParamsResponse) Reset() {
	*x = UpdateWorldParamsResponse{}
	mi := &file_world_world_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorldParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorldParamsResponse) ProtoMessage() {}

func (x *UpdateWorldParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorldParamsResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorldParamsResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateWorldParamsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateWorldParamsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HealthCheckRequest is the request for performing a health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_world_world_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{14}
}

// HealthCheckResponse is the response for the health check
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=world.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_world_world_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_world_world_proto protoreflect.FileDescriptor

const file_world_world_proto_rawDesc = "" +
	"\n" +
	"\x11world/world.proto\x12\x05world\"\xc7\x01\n" +
	"\x12CreateWorldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12)\n" +
	"\x10characters_count\x18\x05 \x01(\x05R\x0fcharactersCount\x12\x1f\n" +
	"\vposts_count\x18\x06 \x01(\x05R\n" +
	"postsCount\"\xce\x03\n" +
	"\rWorldResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x05 \x01(\tR\tcreatorId\x12+\n" +
	"\x11generation_status\x18\x06 \x01(\tR\x10generationStatus\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vusers_count\x18\b \x01(\x05R\n" +
	"usersCount\x12\x1f\n" +
	"\vposts_count\x18\t \x01(\x05R\n" +
	"postsCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tis_joined\x18\f \x01(\bR\bisJoined\x12\x1b\n" +
	"\timage_url\x18\r \x01(\tR\bimageUrl\x12\x19\n" +
	"\bicon_url\x18\x0e \x01(\tR\aiconUrl\x12\x1b\n" +
	"\x06params\x18\x0f \x01(\tH\x00R\x06params\x88\x01\x01B\t\n" +
	"\a_params\"E\n" +
	"\x0fGetWorldRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"q\n" +
	"\x10GetWorldsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"T\n" +
	"\x0eWorldsResponse\x12,\n" +
	"\x06worlds\x18\x01 \x03(\v2\x14.world.WorldResponseR\x06worlds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"F\n" +
	"\x10JoinWorldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\"G\n" +
	"\x11JoinWorldResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"7\n" +
	"\x1aGetGenerationStatusRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\"7\n" +
	"\tStageInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x86\x06\n" +
	"\x1bGetGenerationStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_stage\x18\x02 \x01(\tR\fcurrentStage\x12(\n" +
	"\x06stages\x18\x03 \x03(\v2\x10.world.StageInfoR\x06stages\x12\x1f\n" +
	"\vtasks_total\x18\x04 \x01(\x05R\n" +
	"tasksTotal\x12'\n" +
	"\x0ftasks_completed\x18\x05 \x01(\x05R\x0etasksCompleted\x12!\n" +
	"\ftasks_failed\x18\x06 \x01(\x05R\vtasksFailed\x12%\n" +
	"\x0etask_predicted\x18\a \x01(\x05R\rtaskPredicted\x12#\n" +
	"\rusers_created\x18\b \x01(\x05R\fusersCreated\x12#\n" +
	"\rposts_created\x18\t \x01(\x05R\fpostsCreated\x12'\n" +
	"\x0fusers_predicted\x18\n" +
	" \x01(\x05R\x0eusersPredicted\x12'\n" +
	"\x0fposts_predicted\x18\v \x01(\x05R\x0epostsPredicted\x12-\n" +
	"\x13api_call_limits_llm\x18\f \x01(\x05R\x10apiCallLimitsLlm\x123\n" +
	"\x16api_call_limits_images\x18\r \x01(\x05R\x13apiCallLimitsImages\x12+\n" +
	"\x12api_calls_made_llm\x18\x0e \x01(\x05R\x0fapiCallsMadeLlm\x121\n" +
	"\x15api_calls_made_images\x18\x0f \x01(\x05R\x12apiCallsMadeImages\x12$\n" +
	"\x0ellm_cost_total\x18\x10 \x01(\x01R\fllmCostTotal\x12(\n" +
	"\x10image_cost_total\x18\x11 \x01(\x01R\x0eimageCostTotal\x12\x1d\n" +
	"\n" +
	"created_at\x18\x12 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\tR\tupdatedAt\"p\n" +
	"\x17UpdateWorldImageRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\x12\x1d\n" +
	"\n" +
	"image_uuid\x18\x02 \x01(\tR\timageUuid\x12\x1b\n" +
	"\ticon_uuid\x18\x03 \x01(\tR\biconUuid\"N\n" +
	"\x18UpdateWorldImageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x18UpdateWorldParamsRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\x12\x16\n" +
	"\x06params\x18\x02 \x01(\tR\x06params\"O\n" +
	"\x19UpdateWorldParamsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12HealthCheckRequest\"\x93\x01\n" +
	"\x13HealthCheckResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.world.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xe6\x04\n" +
	"\fWorldService\x12@\n" +
	"\vCreateWorld\x12\x19.world.CreateWorldRequest\x1a\x14.world.WorldResponse\"\x00\x12:\n" +
	"\bGetWorld\x12\x16.world.GetWorldRequest\x1a\x14.world.WorldResponse\"\x00\x12=\n" +
	"\tGetWorlds\x12\x17.world.GetWorldsRequest\x1a\x15.world.WorldsResponse\"\x00\x12@\n" +
	"\tJoinWorld\x12\x17.world.JoinWorldRequest\x1a\x18.world.JoinWorldResponse\"\x00\x12U\n" +
	"\x10UpdateWorldImage\x12\x1e.world.UpdateWorldImageRequest\x1a\x1f.world.UpdateWorldImageResponse\"\x00\x12X\n" +
	"\x11UpdateWorldParams\x12\x1f.world.UpdateWorldParamsRequest\x1a .world.UpdateWorldParamsResponse\"\x00\x12^\n" +
	"\x13GetGenerationStatus\x12!.world.GetGenerationStatusRequest\x1a\".world.GetGenerationStatusResponse\"\x00\x12F\n" +
	"\vHealthCheck\x12\x19.world.HealthCheckRequest\x1a\x1a.world.HealthCheckResponse\"\x00B,Z*github.com/sdshorin/generia/api/grpc/worldb\x06proto3"

var (
	file_world_world_proto_rawDescOnce sync.Once
	file_world_world_proto_rawDescData []byte
)

func file_world_world_proto_rawDescGZIP() []byte {
	file_world_world_proto_rawDescOnce.Do(func() {
		file_world_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_world_proto_rawDesc), len(file_world_world_proto_rawDesc)))
	})
	return file_world_world_proto_rawDescData
}

var file_world_world_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_world_world_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_world_world_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: world.HealthCheckResponse.ServingStatus
	(*CreateWorldRequest)(nil),             // 1: world.CreateWorldRequest
	(*WorldResponse)(nil),                  // 2: world.WorldResponse
	(*GetWorldRequest)(nil),                // 3: world.GetWorldRequest
	(*GetWorldsRequest)(nil),               // 4: world.GetWorldsRequest
	(*WorldsResponse)(nil),                 // 5: world.WorldsResponse
	(*JoinWorldRequest)(nil),               // 6: world.JoinWorldRequest
	(*JoinWorldResponse)(nil),              // 7: world.JoinWorldResponse
	(*GetGenerationStatusRequest)(nil),     // 8: world.GetGenerationStatusRequest
	(*StageInfo)(nil),                      // 9: world.StageInfo
	(*GetGenerationStatusResponse)(nil),    // 10: world.GetGenerationStatusResponse
	(*UpdateWorldImageRequest)(nil),        // 11: world.UpdateWorldImageRequest
	(*UpdateWorldImageResponse)(nil),       // 12: world.UpdateWorldImageResponse
	(*UpdateWorldParamsRequest)(nil),       // 13: world.UpdateWorldParamsRequest
	(*UpdateWorldParamsResponse)(nil),      // 14: world.UpdateWorldParamsResponse
	(*HealthCheckRequest)(nil),             // 15: world.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 16: world.HealthCheckResponse
}
var file_world_world_proto_depIdxs = []int32{
	2,  // 0: world.WorldsResponse.worlds:type_name -> world.WorldResponse
	9,  // 1: world.GetGenerationStatusResponse.stages:type_name -> world.StageInfo
	0,  // 2: world.HealthCheckResponse.status:type_name -> world.HealthCheckResponse.ServingStatus
	1,  // 3: world.WorldService.CreateWorld:input_type -> world.CreateWorldRequest
	3,  // 4: world.WorldService.GetWorld:input_type -> world.GetWorldRequest
	4,  // 5: world.WorldService.GetWorlds:input_type -> world.GetWorldsRequest
	6,  // 6: world.WorldService.JoinWorld:input_type -> world.JoinWorldRequest
	11, // 7: world.WorldService.UpdateWorldImage:input_type -> world.UpdateWorldImageRequest
	13, // 8: world.WorldService.UpdateWorldParams:input_type -> world.UpdateWorldParamsRequest
	8,  // 9: world.WorldService.GetGenerationStatus:input_type -> world.GetGenerationStatusRequest
	15, // 10: world.WorldService.HealthCheck:input_type -> world.HealthCheckRequest
	2,  // 11: world.WorldService.CreateWorld:output_type -> world.WorldResponse
	2,  // 12: world.WorldService.GetWorld:output_type -> world.WorldResponse
	5,  // 13: world.WorldService.GetWorlds:output_type -> world.WorldsResponse
	7,  // 14: world.WorldService.JoinWorld:output_type -> world.JoinWorldResponse
	12, // 15: world.WorldService.UpdateWorldImage:output_type -> world.UpdateWorldImageResponse
	14, // 16: world.WorldService.UpdateWorldParams:output_type -> world.UpdateWorldParamsResponse
	10, // 17: world.WorldService.GetGenerationStatus:output_type -> world.GetGenerationStatusResponse
	16, // 18: world.WorldService.HealthCheck:output_type -> world.HealthCheckResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_world_world_proto_init() }
func file_world_world_proto_init() {
	if File_world_world_proto != nil {
		return
	}
	file_world_world_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_world_proto_rawDesc), len(file_world_world_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_world_world_proto_goTypes,
		DependencyIndexes: file_world_world_proto_depIdxs,
		EnumInfos:         file_world_world_proto_enumTypes,
		MessageInfos:      file_world_world_proto_msgTypes,
	}.Build()
	File_world_world_proto = out.File
	file_world_world_proto_goTypes = nil
	file_world_world_proto_depIdxs = nil
}
