// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: world/world.proto

package world

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_world_world_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_world_world_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{15, 0}
}

// CreateWorldRequest is the request for creating a new world
type CreateWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorldRequest) Reset() {
	*x = CreateWorldRequest{}
	mi := &file_world_world_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorldRequest) ProtoMessage() {}

func (x *CreateWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorldRequest.ProtoReflect.Descriptor instead.
func (*CreateWorldRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateWorldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorldRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorldRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// WorldResponse contains information about a world
type WorldResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prompt           string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	CreatorId        string                 `protobuf:"bytes,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	GenerationStatus string                 `protobuf:"bytes,6,opt,name=generation_status,json=generationStatus,proto3" json:"generation_status,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	UsersCount       int32                  `protobuf:"varint,8,opt,name=users_count,json=usersCount,proto3" json:"users_count,omitempty"`
	PostsCount       int32                  `protobuf:"varint,9,opt,name=posts_count,json=postsCount,proto3" json:"posts_count,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsJoined         bool                   `protobuf:"varint,12,opt,name=is_joined,json=isJoined,proto3" json:"is_joined,omitempty"`
	IsActive         bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorldResponse) Reset() {
	*x = WorldResponse{}
	mi := &file_world_world_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldResponse) ProtoMessage() {}

func (x *WorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldResponse.ProtoReflect.Descriptor instead.
func (*WorldResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{1}
}

func (x *WorldResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorldResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorldResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorldResponse) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *WorldResponse) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *WorldResponse) GetGenerationStatus() string {
	if x != nil {
		return x.GenerationStatus
	}
	return ""
}

func (x *WorldResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorldResponse) GetUsersCount() int32 {
	if x != nil {
		return x.UsersCount
	}
	return 0
}

func (x *WorldResponse) GetPostsCount() int32 {
	if x != nil {
		return x.PostsCount
	}
	return 0
}

func (x *WorldResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *WorldResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *WorldResponse) GetIsJoined() bool {
	if x != nil {
		return x.IsJoined
	}
	return false
}

func (x *WorldResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// GetWorldRequest is the request for getting a world by ID
type GetWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorldRequest) Reset() {
	*x = GetWorldRequest{}
	mi := &file_world_world_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldRequest) ProtoMessage() {}

func (x *GetWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldRequest.ProtoReflect.Descriptor instead.
func (*GetWorldRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorldRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *GetWorldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetWorldsRequest is the request for getting all worlds available to a user
type GetWorldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // active, archived, all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorldsRequest) Reset() {
	*x = GetWorldsRequest{}
	mi := &file_world_world_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorldsRequest) ProtoMessage() {}

func (x *GetWorldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorldsRequest.ProtoReflect.Descriptor instead.
func (*GetWorldsRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorldsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWorldsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetWorldsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetWorldsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// WorldsResponse contains a list of worlds
type WorldsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worlds        []*WorldResponse       `protobuf:"bytes,1,rep,name=worlds,proto3" json:"worlds,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorldsResponse) Reset() {
	*x = WorldsResponse{}
	mi := &file_world_world_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldsResponse) ProtoMessage() {}

func (x *WorldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldsResponse.ProtoReflect.Descriptor instead.
func (*WorldsResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{4}
}

func (x *WorldsResponse) GetWorlds() []*WorldResponse {
	if x != nil {
		return x.Worlds
	}
	return nil
}

func (x *WorldsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// JoinWorldRequest is the request for joining a world
type JoinWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinWorldRequest) Reset() {
	*x = JoinWorldRequest{}
	mi := &file_world_world_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorldRequest) ProtoMessage() {}

func (x *JoinWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorldRequest.ProtoReflect.Descriptor instead.
func (*JoinWorldRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{5}
}

func (x *JoinWorldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinWorldRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

// JoinWorldResponse is the response for joining a world
type JoinWorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinWorldResponse) Reset() {
	*x = JoinWorldResponse{}
	mi := &file_world_world_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinWorldResponse) ProtoMessage() {}

func (x *JoinWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinWorldResponse.ProtoReflect.Descriptor instead.
func (*JoinWorldResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{6}
}

func (x *JoinWorldResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinWorldResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SetActiveWorldRequest is the request for setting a user's active world
type SetActiveWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveWorldRequest) Reset() {
	*x = SetActiveWorldRequest{}
	mi := &file_world_world_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveWorldRequest) ProtoMessage() {}

func (x *SetActiveWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveWorldRequest.ProtoReflect.Descriptor instead.
func (*SetActiveWorldRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{7}
}

func (x *SetActiveWorldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetActiveWorldRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

// SetActiveWorldResponse is the response for setting a user's active world
type SetActiveWorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetActiveWorldResponse) Reset() {
	*x = SetActiveWorldResponse{}
	mi := &file_world_world_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetActiveWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActiveWorldResponse) ProtoMessage() {}

func (x *SetActiveWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActiveWorldResponse.ProtoReflect.Descriptor instead.
func (*SetActiveWorldResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{8}
}

func (x *SetActiveWorldResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetActiveWorldResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetActiveWorldRequest is the request for getting a user's active world
type GetActiveWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveWorldRequest) Reset() {
	*x = GetActiveWorldRequest{}
	mi := &file_world_world_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveWorldRequest) ProtoMessage() {}

func (x *GetActiveWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveWorldRequest.ProtoReflect.Descriptor instead.
func (*GetActiveWorldRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{9}
}

func (x *GetActiveWorldRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GenerateContentRequest is the request for generating AI content for a world
type GenerateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	UsersCount    int32                  `protobuf:"varint,2,opt,name=users_count,json=usersCount,proto3" json:"users_count,omitempty"`
	PostsCount    int32                  `protobuf:"varint,3,opt,name=posts_count,json=postsCount,proto3" json:"posts_count,omitempty"`
	Force         bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateContentRequest) Reset() {
	*x = GenerateContentRequest{}
	mi := &file_world_world_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContentRequest) ProtoMessage() {}

func (x *GenerateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContentRequest.ProtoReflect.Descriptor instead.
func (*GenerateContentRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateContentRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *GenerateContentRequest) GetUsersCount() int32 {
	if x != nil {
		return x.UsersCount
	}
	return 0
}

func (x *GenerateContentRequest) GetPostsCount() int32 {
	if x != nil {
		return x.PostsCount
	}
	return 0
}

func (x *GenerateContentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// GenerateContentResponse is the response for generating AI content
type GenerateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateContentResponse) Reset() {
	*x = GenerateContentResponse{}
	mi := &file_world_world_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateContentResponse) ProtoMessage() {}

func (x *GenerateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateContentResponse.ProtoReflect.Descriptor instead.
func (*GenerateContentResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateContentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateContentResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// GetGenerationStatusRequest is the request for getting the generation status of a world
type GetGenerationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGenerationStatusRequest) Reset() {
	*x = GetGenerationStatusRequest{}
	mi := &file_world_world_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusRequest) ProtoMessage() {}

func (x *GetGenerationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{12}
}

func (x *GetGenerationStatusRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

// GetGenerationStatusResponse is the response containing generation status info
type GetGenerationStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // pending, in_progress, completed, failed
	Message            string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UsersGenerated     int32                  `protobuf:"varint,3,opt,name=users_generated,json=usersGenerated,proto3" json:"users_generated,omitempty"`
	PostsGenerated     int32                  `protobuf:"varint,4,opt,name=posts_generated,json=postsGenerated,proto3" json:"posts_generated,omitempty"`
	ProgressPercentage float32                `protobuf:"fixed32,5,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetGenerationStatusResponse) Reset() {
	*x = GetGenerationStatusResponse{}
	mi := &file_world_world_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGenerationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenerationStatusResponse) ProtoMessage() {}

func (x *GetGenerationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenerationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGenerationStatusResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{13}
}

func (x *GetGenerationStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetGenerationStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetGenerationStatusResponse) GetUsersGenerated() int32 {
	if x != nil {
		return x.UsersGenerated
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetPostsGenerated() int32 {
	if x != nil {
		return x.PostsGenerated
	}
	return 0
}

func (x *GetGenerationStatusResponse) GetProgressPercentage() float32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

// HealthCheckRequest is the request for performing a health check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_world_world_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{14}
}

// HealthCheckResponse is the response for the health check
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=world.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_world_world_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_world_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_world_world_proto_rawDescGZIP(), []int{15}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

var File_world_world_proto protoreflect.FileDescriptor

const file_world_world_proto_rawDesc = "" +
	"\n" +
	"\x11world/world.proto\x12\x05world\"{\n" +
	"\x12CreateWorldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\"\x8b\x03\n" +
	"\rWorldResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x05 \x01(\tR\tcreatorId\x12+\n" +
	"\x11generation_status\x18\x06 \x01(\tR\x10generationStatus\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1f\n" +
	"\vusers_count\x18\b \x01(\x05R\n" +
	"usersCount\x12\x1f\n" +
	"\vposts_count\x18\t \x01(\x05R\n" +
	"postsCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\tis_joined\x18\f \x01(\bR\bisJoined\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\"E\n" +
	"\x0fGetWorldRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"q\n" +
	"\x10GetWorldsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"T\n" +
	"\x0eWorldsResponse\x12,\n" +
	"\x06worlds\x18\x01 \x03(\v2\x14.world.WorldResponseR\x06worlds\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"F\n" +
	"\x10JoinWorldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\"G\n" +
	"\x11JoinWorldResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x15SetActiveWorldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\"L\n" +
	"\x16SetActiveWorldResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x15GetActiveWorldRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8b\x01\n" +
	"\x16GenerateContentRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\x12\x1f\n" +
	"\vusers_count\x18\x02 \x01(\x05R\n" +
	"usersCount\x12\x1f\n" +
	"\vposts_count\x18\x03 \x01(\x05R\n" +
	"postsCount\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"f\n" +
	"\x17GenerateContentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\"7\n" +
	"\x1aGetGenerationStatusRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\"\xd2\x01\n" +
	"\x1bGetGenerationStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fusers_generated\x18\x03 \x01(\x05R\x0eusersGenerated\x12'\n" +
	"\x0fposts_generated\x18\x04 \x01(\x05R\x0epostsGenerated\x12/\n" +
	"\x13progress_percentage\x18\x05 \x01(\x02R\x12progressPercentage\"\x14\n" +
	"\x12HealthCheckRequest\"\x93\x01\n" +
	"\x13HealthCheckResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.world.HealthCheckResponse.ServingStatusR\x06status\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022\xa2\x05\n" +
	"\fWorldService\x12@\n" +
	"\vCreateWorld\x12\x19.world.CreateWorldRequest\x1a\x14.world.WorldResponse\"\x00\x12:\n" +
	"\bGetWorld\x12\x16.world.GetWorldRequest\x1a\x14.world.WorldResponse\"\x00\x12=\n" +
	"\tGetWorlds\x12\x17.world.GetWorldsRequest\x1a\x15.world.WorldsResponse\"\x00\x12@\n" +
	"\tJoinWorld\x12\x17.world.JoinWorldRequest\x1a\x18.world.JoinWorldResponse\"\x00\x12O\n" +
	"\x0eSetActiveWorld\x12\x1c.world.SetActiveWorldRequest\x1a\x1d.world.SetActiveWorldResponse\"\x00\x12F\n" +
	"\x0eGetActiveWorld\x12\x1c.world.GetActiveWorldRequest\x1a\x14.world.WorldResponse\"\x00\x12R\n" +
	"\x0fGenerateContent\x12\x1d.world.GenerateContentRequest\x1a\x1e.world.GenerateContentResponse\"\x00\x12^\n" +
	"\x13GetGenerationStatus\x12!.world.GetGenerationStatusRequest\x1a\".world.GetGenerationStatusResponse\"\x00\x12F\n" +
	"\vHealthCheck\x12\x19.world.HealthCheckRequest\x1a\x1a.world.HealthCheckResponse\"\x00B,Z*github.com/sdshorin/generia/api/grpc/worldb\x06proto3"

var (
	file_world_world_proto_rawDescOnce sync.Once
	file_world_world_proto_rawDescData []byte
)

func file_world_world_proto_rawDescGZIP() []byte {
	file_world_world_proto_rawDescOnce.Do(func() {
		file_world_world_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_world_world_proto_rawDesc), len(file_world_world_proto_rawDesc)))
	})
	return file_world_world_proto_rawDescData
}

var file_world_world_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_world_world_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_world_world_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: world.HealthCheckResponse.ServingStatus
	(*CreateWorldRequest)(nil),             // 1: world.CreateWorldRequest
	(*WorldResponse)(nil),                  // 2: world.WorldResponse
	(*GetWorldRequest)(nil),                // 3: world.GetWorldRequest
	(*GetWorldsRequest)(nil),               // 4: world.GetWorldsRequest
	(*WorldsResponse)(nil),                 // 5: world.WorldsResponse
	(*JoinWorldRequest)(nil),               // 6: world.JoinWorldRequest
	(*JoinWorldResponse)(nil),              // 7: world.JoinWorldResponse
	(*SetActiveWorldRequest)(nil),          // 8: world.SetActiveWorldRequest
	(*SetActiveWorldResponse)(nil),         // 9: world.SetActiveWorldResponse
	(*GetActiveWorldRequest)(nil),          // 10: world.GetActiveWorldRequest
	(*GenerateContentRequest)(nil),         // 11: world.GenerateContentRequest
	(*GenerateContentResponse)(nil),        // 12: world.GenerateContentResponse
	(*GetGenerationStatusRequest)(nil),     // 13: world.GetGenerationStatusRequest
	(*GetGenerationStatusResponse)(nil),    // 14: world.GetGenerationStatusResponse
	(*HealthCheckRequest)(nil),             // 15: world.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 16: world.HealthCheckResponse
}
var file_world_world_proto_depIdxs = []int32{
	2,  // 0: world.WorldsResponse.worlds:type_name -> world.WorldResponse
	0,  // 1: world.HealthCheckResponse.status:type_name -> world.HealthCheckResponse.ServingStatus
	1,  // 2: world.WorldService.CreateWorld:input_type -> world.CreateWorldRequest
	3,  // 3: world.WorldService.GetWorld:input_type -> world.GetWorldRequest
	4,  // 4: world.WorldService.GetWorlds:input_type -> world.GetWorldsRequest
	6,  // 5: world.WorldService.JoinWorld:input_type -> world.JoinWorldRequest
	8,  // 6: world.WorldService.SetActiveWorld:input_type -> world.SetActiveWorldRequest
	10, // 7: world.WorldService.GetActiveWorld:input_type -> world.GetActiveWorldRequest
	11, // 8: world.WorldService.GenerateContent:input_type -> world.GenerateContentRequest
	13, // 9: world.WorldService.GetGenerationStatus:input_type -> world.GetGenerationStatusRequest
	15, // 10: world.WorldService.HealthCheck:input_type -> world.HealthCheckRequest
	2,  // 11: world.WorldService.CreateWorld:output_type -> world.WorldResponse
	2,  // 12: world.WorldService.GetWorld:output_type -> world.WorldResponse
	5,  // 13: world.WorldService.GetWorlds:output_type -> world.WorldsResponse
	7,  // 14: world.WorldService.JoinWorld:output_type -> world.JoinWorldResponse
	9,  // 15: world.WorldService.SetActiveWorld:output_type -> world.SetActiveWorldResponse
	2,  // 16: world.WorldService.GetActiveWorld:output_type -> world.WorldResponse
	12, // 17: world.WorldService.GenerateContent:output_type -> world.GenerateContentResponse
	14, // 18: world.WorldService.GetGenerationStatus:output_type -> world.GetGenerationStatusResponse
	16, // 19: world.WorldService.HealthCheck:output_type -> world.HealthCheckResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_world_world_proto_init() }
func file_world_world_proto_init() {
	if File_world_world_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_world_world_proto_rawDesc), len(file_world_world_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_world_world_proto_goTypes,
		DependencyIndexes: file_world_world_proto_depIdxs,
		EnumInfos:         file_world_world_proto_enumTypes,
		MessageInfos:      file_world_world_proto_msgTypes,
	}.Build()
	File_world_world_proto = out.File
	file_world_world_proto_goTypes = nil
	file_world_world_proto_depIdxs = nil
}
